name: Sample automation

on:
  workflow_dispatch:    
    inputs:
      tagname:
        type: string
        description: "Tagnames"
      envName:
        type: choice
        description: "Environment Name"
        options:
          - QA1
          - QA2
          - Phase3
          - Phase4
          - Phase5
          - WHBM
          - PlaceOrder
          - placeOrder
jobs:
  map-envs:
    #runs-on: ubuntu-latest
    runs-on: terraform
    steps:
      - id: map-folder
        run: |
          echo "folder-path=Salesforce_Project" >> $GITHUB_OUTPUT
    
    outputs:
      folder-path: ${{ steps.map-folder.outputs.folder-path }}
  run-test:
    name: Run Automation Test Suite
    uses: ./.github/workflows/main.yml
    needs: map-envs
    run: mvn -f pom.xml clean test  -Dcucumber.filter.tags=${{inputs.tagname }} -DEnv=${{inputs.envname}}
