name: Sample automation

on:
  workflow_dispatch:
    inputs:
      envname: 
          type: choice
          description: Environment
          options:
  - QA1
  - QA2
  - CHSQA1
  - SOMAQA1
  - CHSQA2
  - SOMAQA2
  - scratchOrg
       tagname: 
         required: true
         type: string
jobs:
  map-envs:
    #runs-on: ubuntu-latest
    runs-on: terraform
  run-test:
    name: Run Automation Test Suite
    uses: actions/checkout
    needs: map-envs
    run: mvn -f pom.xml clean test  -Dcucumber.filter.tags=${{inputs.tagname }} -DEnv=${{inputs.envname}}
